name: binary
description: Utilities for accessing binary data and bit manipulation in Dart and Flutter
version: 3.0.0
homepage: https://github.com/matanlurey/binary
repository: https://github.com/matanlurey/binary

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  matan: ^1.0.0
  meta: ^1.8.0

dev_dependencies:
  coverage: ^1.3.2
  test: ^1.21.1
